##
## -------------------------------------
## |  Marsuch - Symfony docker  |
## -------------------------------------
##

version: '3.3'
################################################################################
# SERVICES
################################################################################
services:

  # ------------------------------------------------------------
  # Database
  # ------------------------------------------------------------
  database:
    container_name: database
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      symfony:
        aliases:
          - mysql

  # ------------------------------------------------------------
  # php
  # ------------------------------------------------------------
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      symfony:
        aliases:
          - php

  # ------------------------------------------------------------
  # nginx
  # ------------------------------------------------------------
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      symfony:
        aliases:
          - nginx
  # ------------------------------------------------------------
  # npm
  # ------------------------------------------------------------
  npm:
    container_name: npm
    image: node:latest
    volumes:
      - ./app:/var/www/symfony_docker
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/symfony_docker
    entrypoint: ['npm']
    networks:
      symfony:
        aliases:
          - npm
  # ------------------------------------------------------------
  # adminer
  # ------------------------------------------------------------
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DATABASE: symfony
      ADMINER_USER: symfony
      ADMINER_PASSWORD: symfony
      ADMINER_DESIGN: ng9
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      symfony:
        aliases:
          - adminer

################################################################################
# NETWORK
################################################################################
networks:
  symfony:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
################################################################################
# Volumes
################################################################################
volumes:
  db_data:
    driver: local